type User {
  id: ID! @id
  firstName: String!
  lastName: String!
  email: String!
  password: String!
  positionAtWork: String!
  avatar_url: String
  country: String
  created_at: DateTime
  updated_at: DateTime
  status: String
}

type Mutation {
  RegisterUser(
    firstName: String!
    lastName: String!
    email: String!
    password: String!
    positionAtWork: String!
    country: String!
    status: String
  ): User
}
