# Informações virão através do Google OAuth
type User {
    id:            ID!                      @id
    name:          String!                  
    email:         String!                  
    password:      String!                  
    avatar_url:    String                   
    created_at:    DateTime                 
    updated_at:    DateTime                 
    status:        String                   
}
